name: smart_home
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  dio: ^5.9.0
  dotted_border: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  flutter_switch: ^0.3.2
  get_it: ^8.2.0
  google_fonts: ^6.3.2
  heroicons: ^0.10.0
  pinput: ^5.0.2
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images_onboarding/
    - assets/images_sign_in/
    - assets/images_home/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Icon_App.png"
